### ISSUE TITLE
Lock-on with controller breaks when game window loses focus.

### ISSUE THREAD

**Issue by tgiddings** [JohnCorby/ow-vanilla-fix#19]
Steps to reproduce:

1. Be piloting the ship using controller
2. Give a different window focus (such as by using alt+tab)
3. Return to the game
4. Attempt to lock onto something using the controller

The lock on with controller no longer works until you use mouse controls to lock onto at least one thing.

This bug was a major frustration for me when I was recently trying out mods, and I hadn't experienced it before, so I thought it was caused by a common dependency. But apparently, this is a vanilla bug -- it may have been introduced after my vanilla playthroughs.

**Comment by JohnCorby** [comment]
i see new code about window focus, so this might be fixed in vanilla????

**Comment by JohnCorby** [comment]
followed repro steps. lock on still works with vanillafix enabled. idk about disabled, but just have the mod and itll work
