### ISSUE TITLE
[Vanilla Bug Request] Exiting to main menu from the map causes a null-ref in CanvasMapMarker.SetVisibility

### ISSUE THREAD

**Issue by sandsalamand** [JohnCorby/ow-vanilla-fix#2]
This bug is present in the base game with the mod disabled, so it has nothing to do with your CanvasMapMarker patch, but since you're already patching CanvasMapMarker, it might make sense to patch this one too.

Log:
NullReferenceException
Stacktrace: CanvasMapMarker.SetVisibility (System.Boolean value) (at <8c964ab98b85490196fd7e9ef29f2234>:0)
MapMarker.DisableMarker () (at <8c964ab98b85490196fd7e9ef29f2234>:0)
MapMarker.OnDisable () (at <8c964ab98b85490196fd7e9ef29f2234>:0)

**Comment by JohnCorby** [comment]
this hasnt happened to me, and they fixed the canvas bug in patch 13
