### ISSUE TITLE
Cursor Bug

### ISSUE THREAD

**Issue by Anonym2631537** [JohnCorby/ow-vanilla-fix#6]
My Cursor stops existing when i start the game with Vanilla Fix on pls help fast

**Comment by kristiangarcia** [comment]
How did you solve it?

**Comment by max1c** [comment]
Same issue. Menu basically doesn't work with the addon enabled.

**Comment by Anonym2631537** [comment]
i didnt i dont know how

**Comment by JohnCorby** [comment]
are you guys not on 1.1.13? this mod broke when 1.1.13 came out, and the fix i did probably means it doesnt work on older versions anymore

**Comment by JohnCorby** [comment]
okay. i had [dgarroDC](https://github.com/dgarroDC) test this on 1.1.10 and he had the same problem. update your game to the latest version (1.1.13) for vanillafix to work.

if updating doesnt actually work, please post a message here and ill work with you from there.

**Comment by max1c** [comment]
Didn't even realize I was on 1.1.10. Thanks for letting us know. It works on 1.1.13.
